
// This file has been generated by the GUI designer. Do not modify.
namespace ControllerGUI
{
	public partial class confViaje
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label viajeLabel;
		private global::Gtk.Entry viajeEntry;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label spo2Label;
		private global::Gtk.Entry spo2Entry;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label spco2Label;
		private global::Gtk.Entry spco2Entry;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label spco2scrubbLabel;
		private global::Gtk.Entry spco2scrubbEntry;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label hsLabel;
		private global::Gtk.Entry hsEntry;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Button okButton;
		private global::Gtk.Button cancelButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ControllerGUI.confViaje
			this.Name = "ControllerGUI.confViaje";
			this.Title = global::Mono.Unix.Catalog.GetString ("confViaje");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ControllerGUI.confViaje.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.viajeLabel = new global::Gtk.Label ();
			this.viajeLabel.WidthRequest = 90;
			this.viajeLabel.Name = "viajeLabel";
			this.viajeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero Viaje");
			this.hbox1.Add (this.viajeLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.viajeLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.viajeEntry = new global::Gtk.Entry ();
			this.viajeEntry.CanFocus = true;
			this.viajeEntry.Name = "viajeEntry";
			this.viajeEntry.IsEditable = true;
			this.viajeEntry.InvisibleChar = '●';
			this.hbox1.Add (this.viajeEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.viajeEntry]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spo2Label = new global::Gtk.Label ();
			this.spo2Label.WidthRequest = 90;
			this.spo2Label.Name = "spo2Label";
			this.spo2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("SP O2");
			this.hbox2.Add (this.spo2Label);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spo2Label]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spo2Entry = new global::Gtk.Entry ();
			this.spo2Entry.CanFocus = true;
			this.spo2Entry.Name = "spo2Entry";
			this.spo2Entry.IsEditable = true;
			this.spo2Entry.InvisibleChar = '●';
			this.hbox2.Add (this.spo2Entry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spo2Entry]));
			w5.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spco2Label = new global::Gtk.Label ();
			this.spco2Label.WidthRequest = 90;
			this.spco2Label.Name = "spco2Label";
			this.spco2Label.LabelProp = global::Mono.Unix.Catalog.GetString ("SP CO2 VALV");
			this.hbox3.Add (this.spco2Label);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spco2Label]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spco2Entry = new global::Gtk.Entry ();
			this.spco2Entry.CanFocus = true;
			this.spco2Entry.Name = "spco2Entry";
			this.spco2Entry.IsEditable = true;
			this.spco2Entry.InvisibleChar = '●';
			this.hbox3.Add (this.spco2Entry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spco2Entry]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.spco2scrubbLabel = new global::Gtk.Label ();
			this.spco2scrubbLabel.WidthRequest = 90;
			this.spco2scrubbLabel.Name = "spco2scrubbLabel";
			this.spco2scrubbLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("SP CO2 Scrubb");
			this.hbox4.Add (this.spco2scrubbLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.spco2scrubbLabel]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.spco2scrubbEntry = new global::Gtk.Entry ();
			this.spco2scrubbEntry.CanFocus = true;
			this.spco2scrubbEntry.Name = "spco2scrubbEntry";
			this.spco2scrubbEntry.IsEditable = true;
			this.spco2scrubbEntry.InvisibleChar = '●';
			this.hbox4.Add (this.spco2scrubbEntry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.spco2scrubbEntry]));
			w11.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hsLabel = new global::Gtk.Label ();
			this.hsLabel.WidthRequest = 90;
			this.hsLabel.Name = "hsLabel";
			this.hsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Histeresis");
			this.hbox5.Add (this.hsLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hsLabel]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hsEntry = new global::Gtk.Entry ();
			this.hsEntry.CanFocus = true;
			this.hsEntry.Name = "hsEntry";
			this.hsEntry.IsEditable = true;
			this.hsEntry.InvisibleChar = '●';
			this.hbox5.Add (this.hsEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hsEntry]));
			w14.Position = 1;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Homogeneous = true;
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.WidthRequest = 80;
			this.okButton.HeightRequest = 50;
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseUnderline = true;
			// Container child okButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = global::Mono.Unix.Catalog.GetString ("OK");
			w20.UseUnderline = true;
			w17.Add (w20);
			w16.Add (w17);
			this.okButton.Add (w16);
			this.hbox6.Add (this.okButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.okButton]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.WidthRequest = 80;
			this.cancelButton.HeightRequest = 50;
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			// Container child cancelButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w25 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w26 = new global::Gtk.HBox ();
			w26.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w27 = new global::Gtk.Image ();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w26.Add (w27);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w29 = new global::Gtk.Label ();
			w29.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancelar");
			w29.UseUnderline = true;
			w26.Add (w29);
			w25.Add (w26);
			this.cancelButton.Add (w25);
			this.hbox6.Add (this.cancelButton);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.cancelButton]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 5;
			w34.Expand = false;
			w34.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.okButton.Clicked += new global::System.EventHandler (this.OnOkButtonClicked);
			this.cancelButton.Clicked += new global::System.EventHandler (this.OnCancelButtonClicked);
		}
	}
}
